### ISSUE TITLE
how to play this awesome game

### ISSUE THREAD

**Issue by flavioribeiro** [andrewsmedina/jailbreakerz#1]
where can I find the docs?

**Comment by andrewsmedina** [comment]
are u kidding me?

**Comment by rafaelcaricio** [comment]
Plz also forward me the docs.

**Comment by fsouza** [comment]
+1 for docs pls

**Comment by flavioribeiro** [comment]
it seems this project is not maintained anymore. It's sad, my PR is there for 8 long hours...

**Comment by flavioribeiro** [comment]
merged, thanks @flavioribeiro
